# -*- coding: utf-8 -*-
"""numpy_operations

Automatically generated by Colaboratory.

"""

print("hello")

import numpy as np

a=np.array([2,3,4,5,1,23,423])    # creating 1D array

type(a)
a

b=np.array([4,2,2,1,546,34,2])

type(b)

b

a[0]

b[0]

a+b     # adding same D array

a*2

a**2

a+5   # add particular value in each element of array a

x = np.array([[2,5,8],[3,6,1]])    #   2*3 D array

type(x)

x

x[0]

x[0][0]

print(x+7)

x+2

x*2

x

x[1]

z=np.array([  [2,7],[3,8],[2,9],[9,2]  ])

z

x.shape

z.shape

x

x[0]

z[0]

z[0:2]               #for printing range of rows......

z[0:]

z[0:,0]           # print first col

z[0:,1]           # print second col

z[0:2,0]

z

x

x[0:,1]

x[0:,2]

x[0:,0:2]

x[0:,[0,2]]

x

z

z[[0,2]]

z

z[[0,2],[0]]

z[[0,3],[1]]

z[[3],[1]]

z[[0,3],1]

b=np.array([[1,9,7],[3,2,8],[4,5,6],[2,9,0]])

b.shape

b[0:4,[1]]

b[0:,[1]]

b[0:,[2]]

b[[1,2],[1]]

b[1:4,2]

b[1:4,[0,2]]

x

x1=x.reshape(3,2)

x1

np.zeros((3,6))

np.zeros((3,4),dtype=int)

np.ones((2,3))

np.full((4,5),9)

import time
for i in dir(np):
    if 'zer' in i:
      print(i)
      time.sleep(1)

[i for i in dir(np) if 'zer' in  i]

# T2) generate 3*2  &  2*5  2D array with random element and save this data into two sep file

