# -*- coding: utf-8 -*-
"""pynumber1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OgV93gloIMnvNnPDi4-MgCyXpdu882Fi
"""

import numpy as np

row=int(input("Enter the numberof rows"))
col=int(input("Enter the number of column"))

array=np.random.rand(row,col)

array

np.savetxt("array.txt",array)

result=np.loadtxt("array.txt")

result

