# -*- coding: utf-8 -*-
"""pynumber2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_swyhMYVANB7lu6YfgpsSHLDPIum3oHJ
"""

import numpy as np

array=np.arange(100,200,5)

array

array1=array[0:16].reshape(8,2)

array1

